# Generated by Django 4.1.13 on 2024-10-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_job_job_description_add_job_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_job',
            name='location',
        ),
        migrations.AlterField(
            model_name='add_job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('apprenticeship', 'Apprenticeship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='job_level',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'Vice President'), ('c_level', 'C-Level')], max_length=100),
        ),
        migrations.AlterField(
            model_name='add_job',
            name='reference_link',
            field=models.URLField(),
        ),
    ]
