# Generated by Django 4.1.13 on 2024-10-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_add_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='add_job',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
