# Generated by Django 4.1.13 on 2024-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
