# Generated by Django 4.1.13 on 2024-10-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_job',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
