# Generated by Django 4.1.13 on 2024-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_add_job_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_email_template',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
