# Generated by Django 4.1.13 on 2024-10-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

###########################################
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_default_user(apps, schema_editor):
    Add_Job = apps.get_model('tracker', 'Add_Job')
    User = apps.get_model('auth', 'User')  # Get the User model
    default_user = User.objects.first()  # Get the first user
    if default_user:
        Add_Job.objects.filter(user=None).update(user=default_user)  # Update existing records


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_add_email_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='auth.User'),
        ),
    ]