# Generated by Django 4.1.13 on 2024-10-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job',
            name='company_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
