# Generated by Django 5.1.2 on 2024-11-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_otp_user_delete_add_email_template_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
