# Generated by Django 5.1.2 on 2024-12-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_remove_feedback_email_remove_feedback_feedback_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
