# Generated by Django 5.1.2 on 2024-12-31 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_feedback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='additional_comments',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfaction',
        ),
        migrations.AddField(
            model_name='feedback',
            name='discovery',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('word_of_mouth', 'Word of Mouth'), ('search_engine', 'Search Engine'), ('friend', 'Friend/Colleague'), ('advertisement', 'Advertisement'), ('other', 'Other')], default='social_media', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='navigation',
            field=models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('neutral', 'Neutral'), ('difficult', 'Difficult'), ('very_difficult', 'Very Difficult')], default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
