# Generated by Django 5.1.2 on 2025-02-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_remove_project_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='platform_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proficiency_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proficiency_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proficiency_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('profile_link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='tracker.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tracker.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tracker.userprofile')),
            ],
        ),
    ]
