# Generated by Django 5.1.2 on 2025-02-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_remove_userprofile_platform_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='SocialProfile',
        ),
    ]
