# Generated by Django 5.1.2 on 2025-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_alter_userprofile_job_title_alter_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='platform_name',
            field=models.CharField(max_length=255),
        ),
    ]
